# -------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
# SoftServe ITA
# -------------------------------------------------------------



on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
